In [12]:
import pandas as pd

dataset = pd.read_csv('train.csv')

# Onehot encoding

In [2]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

# Define dataframe's function and the column to return a dataframe later OHE
def OneHotEncoding(df, column):
    label = LabelEncoder()
    encoding=label.fit_transform(df[column]).reshape(-1,1)
    encoder = OneHotEncoder(sparse=False)
    column = [column+ "_"+ str(i) for i in label.classes_]
    data = encoder.fit_transform(encoding)
    return(pd.DataFrame(data,columns =column))

In [3]:
#split categorical data from numerical date
types = pd.DataFrame(dataset.dtypes)
numeric_columns = list(set(types.index[types[0] =="int64"].values) - set(["SalePrice"]))

#create dataframe with ready features
all_data_finish = dataset[numeric_columns]

#create output dataframe
objetive = dataset["SalePrice"]

all_data_finish

,OverallCond,Id,MoSold,LowQualFinSF,BedroomAbvGr,EnclosedPorch,3SsnPorch,YrSold,GarageArea,BsmtUnfSF,...,TotRmsAbvGrd,YearRemodAdd,PoolArea,MSSubClass,BsmtFinSF2,KitchenAbvGr,MiscVal,YearBuilt,TotalBsmtSF,GarageCars
0,5,1,2,0,3,0,0,2008,548,150,...,8,2003,0,60,0,1,0,2003,856,2
1,8,2,5,0,3,0,0,2007,460,284,...,6,1976,0,20,0,1,0,1976,1262,2
2,5,3,9,0,3,0,0,2008,608,434,...,6,2002,0,60,0,1,0,2001,920,2
3,5,4,2,0,3,272,0,2006,642,540,...,7,1970,0,70,0,1,0,1915,756,3
4,5,5,12,0,4,0,0,2008,836,490,...,9,2000,0,60,0,1,0,2000,1145,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,5,1456,8,0,3,0,0,2007,460,953,...,7,2000,0,60,0,1,0,1999,953,2
1456,6,1457,2,0,3,0,0,2010,500,589,...,7,1988,0,20,163,1,0,1978,1542,2
1457,9,1458,5,0,4,0,0,2010,252,877,...,9,2006,0,70,0,1,2500,1941,1152,1
1458,6,1459,4,0,2,112,0,2010,240,0,...,5,1996,0,20,1029,1,0,1950,1078,1
1459,6,1460,6,0,3,0,0,2008,276,136,...,6,1965,0,20,290,1,0,1965,1256,1

In [4]:
#encoding categories and add finished column to dataframe with ready features
categories = types.index[types[0] == 'O'].values
for column in categories:
    df = OneHotEncoding(dataset,column)
    all_data_finish = pd.concat([all_data_finish,df],axis=1)
    print("Column ",column, " tranform!")

Column  MSZoning  tranform!
Column  Street  tranform!

TypeError: Encoders require their input to be uniformly strings or numbers. Got ['float', 'str']

In [5]:
all_data_finish

,OverallCond,Id,MoSold,LowQualFinSF,BedroomAbvGr,EnclosedPorch,3SsnPorch,YrSold,GarageArea,BsmtUnfSF,...,YearBuilt,TotalBsmtSF,GarageCars,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Grvl,Street_Pave
0,5,1,2,0,3,0,0,2008,548,150,...,2003,856,2,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,8,2,5,0,3,0,0,2007,460,284,...,1976,1262,2,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,5,3,9,0,3,0,0,2008,608,434,...,2001,920,2,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,5,4,2,0,3,272,0,2006,642,540,...,1915,756,3,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,5,5,12,0,4,0,0,2008,836,490,...,2000,1145,3,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,5,1456,8,0,3,0,0,2007,460,953,...,1999,953,2,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1456,6,1457,2,0,3,0,0,2010,500,589,...,1978,1542,2,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1457,9,1458,5,0,4,0,0,2010,252,877,...,1941,1152,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1458,6,1459,4,0,2,112,0,2010,240,0,...,1950,1078,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1459,6,1460,6,0,3,0,0,2008,276,136,...,1965,1256,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0

# Feature hashing

In [13]:
gg = dataset[['MSZoning','Utilities']]
gg.head()

  MSZoning Utilities
0       RL    AllPub
1       RL    AllPub
2       RL    AllPub
3       RL    AllPub
4       RL    AllPub

In [29]:
# n_features : integer, optional
#        The number of features (columns) in the output matrices. Small numbers
#        of features are likely to cause hash collisions, but large numbers
#        will cause larger coefficient dimensions in linear learners.

from sklearn.feature_extraction import FeatureHasher
gg_hash = gg.copy()
for column in gg.columns:
    gg_hash[column]=gg[column].astype('str')      
hashing=FeatureHasher(n_features=10, input_type='string')
final=hashing.transform(gg_hash.values)

In [30]:
final.shape

(1460, 10)

In [31]:
type(final)

scipy.sparse.csr.csr_matrix

In [32]:
final.todense()

matrix([[ 0.,  0., -1., ...,  0.,  0.,  0.],
        [ 0.,  0., -1., ...,  0.,  0.,  0.],
        [ 0.,  0., -1., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0., -1., ...,  0.,  0.,  0.],
        [ 0.,  0., -1., ...,  0.,  0.,  0.],
        [ 0.,  0., -1., ...,  0.,  0.,  0.]])

In [33]:
print('train data set has got {} rows and {} columns'.format(final.shape[0],final.shape[1]))

train data set has got 1460 rows and 10 columns

In [ ]:
Model_logistic(final,y)

# KDD Orange Competition Best Solution

In the winning solution of the KDD 2009 cup: “Winning the KDD Cup Orange Challenge with Ensemble Selection”, the authors limited one-hot encoding to the 10 most frequent labels of the variable which means that they would make one binary variable for each of the 10 most frequent labels only. It is equivalent to grouping all the other labels under a new category that in this case, will be dropped. Thus, the 10 new dummy variables indicate if one of the 10 most frequent labels is present (1) or not (0) for a particular observation.

In [ ]:
top_10 = [x for x in df['categorical'].value_counts().sort_values(ascending=False).head(10).index]

for i in top_10:
    df[i] = np.where(df['categorical']==i, 1, 0)